// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.MonitoringServiceApiCaller.Models
{
    using Lykke.MonitoringServiceApiCaller;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ListDataMonitoringObjectModel
    {
        /// <summary>
        /// Initializes a new instance of the ListDataMonitoringObjectModel
        /// class.
        /// </summary>
        public ListDataMonitoringObjectModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ListDataMonitoringObjectModel
        /// class.
        /// </summary>
        public ListDataMonitoringObjectModel(IList<MonitoringObjectModel> data = default(IList<MonitoringObjectModel>))
        {
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IList<MonitoringObjectModel> Data { get; set; }

    }
}
