// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.MonitoringServiceApiCaller.Models
{
    using Lykke.MonitoringServiceApiCaller;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MonitoringObjectModel
    {
        /// <summary>
        /// Initializes a new instance of the MonitoringObjectModel class.
        /// </summary>
        public MonitoringObjectModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MonitoringObjectModel class.
        /// </summary>
        public MonitoringObjectModel(string serviceName = default(string), string version = default(string), System.DateTime? lastPing = default(System.DateTime?), System.DateTime? skipUntil = default(System.DateTime?), string url = default(string))
        {
            ServiceName = serviceName;
            Version = version;
            LastPing = lastPing;
            SkipUntil = skipUntil;
            Url = url;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serviceName")]
        public string ServiceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastPing")]
        public System.DateTime? LastPing { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "skipUntil")]
        public System.DateTime? SkipUntil { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
