// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MonitoringServiceApiCaller
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for MonitoringService.
    /// </summary>
    internal static partial class MonitoringServiceExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static ListDataMonitoringObjectModel ApiMonitoringGet(this IMonitoringService operations)
            {
                return operations.ApiMonitoringGetAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ListDataMonitoringObjectModel> ApiMonitoringGetAsync(this IMonitoringService operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiMonitoringGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static void ApiMonitoringPingPost(this IMonitoringService operations, MonitoringObjectPingModel model = default(MonitoringObjectPingModel))
            {
                operations.ApiMonitoringPingPostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiMonitoringPingPostAsync(this IMonitoringService operations, MonitoringObjectPingModel model = default(MonitoringObjectPingModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.ApiMonitoringPingPostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
