// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.MonitoringServiceApiCaller.Models
{
    using Lykke.MonitoringServiceApiCaller;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MonitoringObjectUnmuteModel
    {
        /// <summary>
        /// Initializes a new instance of the MonitoringObjectUnmuteModel
        /// class.
        /// </summary>
        public MonitoringObjectUnmuteModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MonitoringObjectUnmuteModel
        /// class.
        /// </summary>
        public MonitoringObjectUnmuteModel(string serviceName = default(string))
        {
            ServiceName = serviceName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serviceName")]
        public string ServiceName { get; set; }

    }
}
